// A short, orientation-independent core meaning for every one of the 78 cards.
// Kept separate from deck.ts so the meanings can be edited or swapped by a
// future plugin without touching the deck's structural data. Keyed by card id.

export const ESSENCES: Record<string, string> = {
  // ---- Major Arcana ----
  'major-00': 'The eternal beginner, stepping off the cliff in perfect trust.',
  'major-01': 'The channel where will becomes matter.',
  'major-02': 'The keeper of the threshold between the known and the unknown.',
  'major-03': 'The great mother: life creating more life.',
  'major-04': 'The father: order imposed upon chaos.',
  'major-05': 'The bridge between the divine and the crowd.',
  'major-06': 'The union of opposites and the choice it demands.',
  'major-07': 'Opposing forces yoked to a single will.',
  'major-08': 'Power made gentle: the soul mastering the beast.',
  'major-09': 'The lantern-bearer who seeks the light within.',
  'major-10': 'The turning of fate: nothing holds still.',
  'major-11': 'The blade and the scale: every act answered in kind.',
  'major-12': 'Surrender that turns the world right-side up.',
  'major-13': 'The great transition: one door closes so another opens.',
  'major-14': 'The alchemist blending extremes into one.',
  'major-15': 'The chains we forge and choose to wear.',
  'major-16': 'The lightning that razes what was built on lies.',
  'major-17': 'The quiet promise of hope after ruin.',
  'major-18': 'The dreaming dark where nothing is certain.',
  'major-19': 'Undimmed joy: life lit from within.',
  'major-20': 'The trumpet call to rise and be remade.',
  'major-21': 'The circle complete: the dance come home.',

  // ---- Wands (Fire: drive, passion, creation) ----
  'wands-01': 'The first spark of creative fire.',
  'wands-02': 'The horizon weighed before the leap.',
  'wands-03': 'Vision cast outward, ships upon the sea.',
  'wands-04': 'The joyful threshold of arrival.',
  'wands-05': 'The scramble of many wills at once.',
  'wands-06': 'The homecoming of the victor.',
  'wands-07': 'The lone defender of high ground.',
  'wands-08': 'Swift arrows loosed toward their mark.',
  'wands-09': 'The battered guardian who will not fall.',
  'wands-10': 'The heavy load of all one has taken on.',
  'wands-11': 'The restless spark of a new passion.',
  'wands-12': 'Fire on the gallop, headlong and bold.',
  'wands-13': 'The radiant flame others gather toward.',
  'wands-14': 'The visionary who rules by bold fire.',

  // ---- Cups (Water: heart, feeling, connection) ----
  'cups-01': 'The overflowing cup of new feeling.',
  'cups-02': 'Two hearts meeting as equals.',
  'cups-03': 'The circle of friends, cups raised.',
  'cups-04': 'The heart turned inward, a gift unseen.',
  'cups-05': 'Grief bent over what was spilled.',
  'cups-06': 'The sweet, safe country of memory.',
  'cups-07': 'A haze of tempting, shifting dreams.',
  'cups-08': 'The quiet walk away toward something truer.',
  'cups-09': 'The satisfied heart, its wish fulfilled.',
  'cups-10': 'The rainbow of a family made whole.',
  'cups-11': 'A gentle message rising from the deep.',
  'cups-12': "The romantic who follows the heart's tide.",
  'cups-13': 'Still waters of deep compassion.',
  'cups-14': 'The calm master of his own feeling.',

  // ---- Swords (Air: mind, truth, conflict) ----
  'swords-01': 'The clean edge of sudden clarity.',
  'swords-02': 'The blindfolded truce of a mind at war.',
  'swords-03': 'The heart pierced by unwanted truth.',
  'swords-04': 'The needed rest of a weary mind.',
  'swords-05': 'The bitter cost of a hollow victory.',
  'swords-06': 'The slow crossing to calmer water.',
  'swords-07': 'The cunning exit, spoils in hand.',
  'swords-08': "The prison built of one's own thoughts.",
  'swords-09': 'The sleepless dread of the small hours.',
  'swords-10': 'The final blow: rock bottom reached.',
  'swords-11': 'The keen, watchful, curious mind.',
  'swords-12': 'Thought charging headlong into action.',
  'swords-13': 'The clear, unclouded, truth-telling mind.',
  'swords-14': 'Authority ruling by reason and truth.',

  // ---- Pentacles (Earth: work, money, the material) ----
  'pentacles-01': 'The seed of tangible prosperity.',
  'pentacles-02': 'The dance of keeping every coin in motion.',
  'pentacles-03': 'Skilled hands building something greater.',
  'pentacles-04': 'The tight grip that guards what it holds.',
  'pentacles-05': 'The cold outside the lit window.',
  'pentacles-06': 'The scales of giving and receiving.',
  'pentacles-07': 'The patient wait upon a slow harvest.',
  'pentacles-08': 'Repetition honed into mastery.',
  'pentacles-09': 'The refined garden earned alone.',
  'pentacles-10': 'The lasting wealth of legacy.',
  'pentacles-11': 'The student apprenticed to the real.',
  'pentacles-12': 'The steady, dependable march of duty.',
  'pentacles-13': 'The nurturing keeper of a warm hearth.',
  'pentacles-14': 'The grounded master of the material realm.',
}
