// Canonical approved AllPath footer mirror; public assets and links use the branded site.
import Link from 'next/link'

// Founder-approved shared footer. Keep outside editable page content.
export function SiteFooter() {
  return <div className="final-footer" data-footer-version="2026-09-27-contact">
    <style dangerouslySetInnerHTML={{ __html: CSS }} />
    <footer className="site">
      <div className="cosmic-dust" aria-hidden="true" /><div className="shooting-stars" aria-hidden="true"><i /><i /></div>
      <span className="footer-emblem"><img src="https://allpathproperties.com/home/allpath-footer.webp" alt="AllPath Education Solutions" width={80} height={76} /><span className="footer-letter-gold" aria-hidden="true" style={{ maskImage: 'url(https://allpathproperties.com/home/allpath-footer.webp)', WebkitMaskImage: 'url(https://allpathproperties.com/home/allpath-footer.webp)' }} /></span>
      <nav aria-label="Footer"><Link href="https://allpathproperties.com/">Home</Link><Link href="https://allpathproperties.com/about">About Us</Link><Link href="https://allpathproperties.com/samples#learning-labs">Universe</Link><Link href="https://allpathproperties.com/contact">Contact Us</Link></nav>
      <span className="footer-emblem"><img src="https://allpathproperties.com/home/synchpathways-footer.webp" alt="SynchPathways Programming Atlas" width={80} height={76} /><span className="footer-letter-gold" aria-hidden="true" style={{ maskImage: 'url(https://allpathproperties.com/home/synchpathways-footer.webp)', WebkitMaskImage: 'url(https://allpathproperties.com/home/synchpathways-footer.webp)' }} /></span>
      <div className="copyright"><span className="footer-brands"><span>AllPath Education Solutions</span><span className="footer-brand-dot" aria-hidden="true">•</span><span>SynchPathways Programming Atlas</span></span><span className="footer-rights">© 2026. All rights reserved.</span></div>
    </footer>
  </div>
}
const CSS = ".final-footer{position:relative;isolation:isolate;width:100%;padding-top:18px;color:#fff1c4;font-family:Arial,sans-serif}.final-footer footer.site{position:relative;isolation:isolate;display:grid;grid-template-columns:80px minmax(0,1fr) 80px;gap:4px 20px;align-items:center;box-sizing:border-box;min-height:96px;padding:10px clamp(16px,3vw,48px);border:0;background:transparent}.final-footer footer:before{content:'';position:absolute;inset:-8px 0 0;z-index:-1;background:radial-gradient(ellipse at 50% 100%,#431275,#17052e 68%,#10051f);mask-image:linear-gradient(transparent,#000 20px,#000 calc(100% - 6px),transparent);border-radius:50% 50% 0 0 / 12px 12px 0 0}.final-footer footer:after{content:'';position:absolute;inset:2px 8px 5px;background:#38125f;filter:blur(14px);opacity:.55;z-index:-2}.final-footer img{width:80px;height:72px;object-fit:contain;grid-row:1/4;filter:brightness(1.6) contrast(1.2) drop-shadow(0 0 5px #f5c65c)}.final-footer img:last-of-type{grid-column:3}.final-footer nav{grid-column:2;grid-row:1;display:flex;justify-content:center;gap:24px}.final-footer nav a{font-size:12px;color:#fff1c4;text-decoration:none;white-space:nowrap;padding:6px}.final-footer .fl{display:none!important}.final-footer .copyright{grid-column:2;grid-row:2;text-align:center;font-size:10px;line-height:1.4}.final-footer .copyright br{display:none}.final-footer .cosmic-dust,.final-footer .shooting-stars{position:absolute;inset:0;z-index:-1;pointer-events:none;overflow:hidden;mask-image:linear-gradient(transparent,#000 20px,#000 90%,transparent)}.final-footer .cosmic-dust{background-image:radial-gradient(circle,#ffe293 1px,transparent 2px);background-size:83px 47px;animation:dust 12s ease-in-out infinite alternate}.final-footer .shooting-stars i{position:absolute;top:5%;left:15%;width:90px;height:1px;background:linear-gradient(90deg,transparent,#ffe59b);animation:shoot 9s linear infinite}.final-footer .shooting-stars i:nth-child(2){left:65%;animation-delay:4s;animation-duration:13s}@keyframes dust{from{opacity:.25;transform:translateY(0)}to{opacity:.65;transform:translateY(-8px)}}@keyframes shoot{0%,78%{opacity:0;transform:translate(-100px,-25px) rotate(20deg)}80%{opacity:.9}94%,100%{opacity:0;transform:translate(280px,100px) rotate(20deg)}}@media(max-width:700px){.final-footer footer.site{grid-template-columns:60px minmax(0,1fr) 60px;gap:8px;padding:14px 16px}.final-footer img{width:60px;height:60px}.final-footer nav{gap:4px}.final-footer nav a{font-size:11px;padding:4px}.final-footer .copyright br{display:block}}@media(prefers-reduced-motion:reduce){.final-footer .cosmic-dust,.final-footer .shooting-stars i{animation:none}.final-footer .shooting-stars{display:none}}\n.final-footer{margin-top:auto}"
