import type { OliHubSurface, OliHubSurfaceId } from './specialist-types'

export const OLI_HUB_SURFACES: Record<OliHubSurfaceId, OliHubSurface> = {
  'mothership-vault': {
    id: 'mothership-vault',
    name: 'Mothership Vault',
    description: 'Owner-controlled source, project, design, evidence, and approved-asset vault.',
    purpose: 'Preserve originals, approved versions, project/source lineage, and reusable authorized assets without flattening separate product histories.',
    route: '/oli#vault',
    requiredReadScopes: ['mothership.vault.read'],
    optionalWriteScopes: ['mothership.vault.write-candidate', 'commander.report.write'],
    founderGate: true,
    dataClasses: ['INTERNAL', 'CLIENT', 'EDUCATION_RECORD', 'HEALTH', 'RESTRICTED'],
    rules: [
      'Original source files and prior approved versions remain preserved.',
      'New material enters as a candidate or revision rather than silently overwriting approved source.',
      'Target products inherit only assets and records explicitly authorized for that target.',
      'Restricted, health, education, client, and research data retain their own access boundaries.',
      'A specialist mode may request a vault source, but cannot expand its own access to retrieve it.',
    ],
  },
  'manifesto-scribe': {
    id: 'manifesto-scribe',
    name: 'Manuscript + Living Blueprint Scribe',
    description: 'The evolving governance, philosophy, system record, Scribe history, and owner-reviewed addendum lane.',
    purpose: 'Let Oli and specialist stacks read current operating rules, preserve provenance, and propose addenda while keeping canonical promotion owner-controlled.',
    route: '/oli#manifesto',
    requiredReadScopes: ['mothership.manifesto.read'],
    optionalWriteScopes: ['mothership.manifesto.propose-addendum', 'scribe.addendum.propose', 'commander.report.write'],
    founderGate: true,
    dataClasses: ['PUBLIC', 'INTERNAL', 'CLIENT', 'RESTRICTED'],
    rules: [
      'Every material Oli stack reads the current applicable manuscript/governance record before consequential work.',
      'Verified outcomes may feed Scribe history and addendum candidates.',
      'No automated process may silently rewrite canonical Blueprint text or chapter order.',
      'Addendum proposals preserve source, date, author/agent, evidence class, permissions, and checker state.',
      'Owner approval is required to promote a candidate into canonical manuscript authority.',
    ],
  },
  'commander-log': {
    id: 'commander-log',
    name: 'Commander Log + Daily Debrief',
    description: 'The durable operational history for meaningful Oli routes, approvals, outcomes, blockers, and verified changes.',
    purpose: 'Keep every specialist stack in one visible operating history so work does not disappear into isolated product chats.',
    route: '/oli#commander-log',
    requiredReadScopes: ['mothership.commander-log.read'],
    optionalWriteScopes: ['mothership.commander-log.write', 'mothership.daily-debrief.read', 'mothership.daily-debrief.write', 'commander.report.write'],
    founderGate: false,
    dataClasses: ['PUBLIC', 'INTERNAL', 'CLIENT', 'EDUCATION_RECORD', 'HEALTH', 'RESTRICTED'],
    rules: [
      'Log meaningful state transitions, decisions, approvals, outcomes, blockers, and source pushes rather than noisy raw telemetry.',
      'Agent-originated entries remain labeled as agent-originated and are never represented as owner-authored.',
      'Logs distinguish documented fact, reported experience, interpretation, hypothesis, contradiction, and unknown.',
      'Sensitive details are minimized or referenced by protected source ID rather than copied into a broader log.',
      'Daily Debrief summarizes the useful operational picture and links back to exact source/task/event records.',
    ],
  },
  'source-intelligence': {
    id: 'source-intelligence',
    name: 'Source Intelligence + Permissions',
    description: 'Verified capability, connector, plan, permission, limitation, checker, and task-routing truth.',
    purpose: 'Let Oli explain what each source can actually do now and stop theoretical provider features from becoming false capability claims.',
    route: '/oli#sources',
    requiredReadScopes: ['mothership.source-intelligence.read'],
    optionalWriteScopes: ['commander.report.write'],
    founderGate: false,
    dataClasses: ['INTERNAL', 'RESTRICTED'],
    rules: [
      'Invitation, authentication, permission, task ownership, and canonical authority remain separate states.',
      'Only verified current capabilities may be routed as available.',
      'New paid services, new permissions, secret changes, and production authority remain owner-gated.',
      'Capability telemetry may improve routing but never grants permissions automatically.',
    ],
  },
  'specialist-stacks': {
    id: 'specialist-stacks',
    name: 'Oli Specialist Stacks',
    description: 'Web, Esoteric/Tarot, Music, Education, Industrial/OSHA, and Medical specialist modes under one Commander identity.',
    purpose: 'Route each question to the right bounded capability set while preserving one Oli identity, one governance spine, and one return path to Commander.',
    route: '/oli#stacks',
    requiredReadScopes: [],
    optionalWriteScopes: ['commander.report.write', 'scribe.addendum.propose'],
    founderGate: false,
    dataClasses: ['PUBLIC', 'INTERNAL', 'CLIENT', 'EDUCATION_RECORD', 'HEALTH', 'RESTRICTED'],
    rules: [
      'A stack is a mode, not a separate Oli or competing brain.',
      'Each stack checks permissions and data class before tool use.',
      'High-stakes professional lanes preserve human-review and emergency escalation rules.',
      'Verified outcomes may improve future routing and source suggestions, but never permissions.',
    ],
  },
}

export function listOliHubSurfaces(): OliHubSurface[] {
  return Object.values(OLI_HUB_SURFACES)
}
